### ISSUE TITLE
Error when deploying rke2 on Windows

### ISSUE THREAD

**Issue by MichaelTrip** [rancher/rke2#1691]
**Environmental Info:**
RKE2 Version: 
rke2.exe version v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)

Node(s) CPU architecture, OS, and Version: 

3 Linux: Dataplane, etcd and master
1 Windows server 2019 eval: worker

Cluster Configuration:
3 servers and one agent

**Describe the bug:**
When trying to install the rke2 agent on Windows it keeps on hanging in a loop. This can be seen when running 
```
rke2.exe agent
```

**Steps To Reproduce:**

- Installed RKE2: 
- Following this documentation: https://docs.rke2.io/install/quickstart/#0-prepare-the-windows-agent-node and further.
**Expected behavior:**
A working Windows node

**Actual behavior:**
After running the steps and starting `rke2.exe agent` a error pops up, see below.

**Additional context / logs:**

```
2021-08-23 15:22:11.404 [INFO][4548] felix/config_params.go 449: Value set to 'none', replacing with zero-value: "".
2021-08-23 15:22:11.404 [INFO][4548] felix/config_params.go 468: Parsed value for LogSeverityFile:  (from environment variable)
2021-08-23 15:22:11.404 [INFO][4548] felix/config_params.go 432: Parsing value for LogSeveritySys: none (from environment variable)
... dropped 28 logs ...
2021-08-23 15:22:11.404 [INFO][4548] felix/usagerep.go 91: Waiting before first check-in delay=5m3.186s
... dropped 25 logs ...
2021-08-23 15:22:11.926 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:11.926 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=522.3856999999999
2021-08-23 15:22:11.926 [INFO][4548] felix/win_dataplane.go 312: Completed first update to dataplane. secsSinceStart=3.8060229
2021-08-23 15:22:11.927 [INFO][4548] felix/health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:false} name="win_dataplane" newReport=&health.HealthReport{Live:true, Ready:true}
time="2021-08-23T15:22:15+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:16.999 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:17.002 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:17.002 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=2.7129
2021-08-23 15:22:17.217 [INFO][4152] startup/startup.go 390: Early log level set to info
2021-08-23 15:22:17.217 [INFO][4152] startup/startup.go 406: Using NODENAME environment for node name kube-win
2021-08-23 15:22:17.217 [INFO][4152] startup/startup.go 418: Determined node name: kube-win
2021-08-23 15:22:17.217 [INFO][4152] startup/startup.go 103: Starting node kube-win with version v3.19.1
2021-08-23 15:22:17.311 [INFO][4152] startup/startup.go 115: Skipping datastore connection test
2021-08-23 15:22:17.535 [INFO][4152] startup/startup.go 774: Using autodetected IPv4 address on interface vEthernet (Ethernet): 172.16.1.83/24
2021-08-23 15:22:17.600 [INFO][4152] startup/startup.go 851: No AS number configured on node resource, using global value
2021-08-23 15:22:17.636 [INFO][4152] startup/startup.go 967: Selected default IP pool is '192.168.0.0/16'
2021-08-23 15:22:17.715 [INFO][4152] startup/startup.go 228: Using node name: kube-win
2021-08-23 15:22:17.716 [INFO][4152] startup/startup_windows.go 66: Backend networking is vxlan, ensure vxlan network.
2021-08-23 15:22:17.719 [INFO][4152] startup/ipam.go 1895: Ensure block for host kube-win, ipv4 attr &{3 1 windows-reserved-ipam-handle windows host rsvd} ipv6 attr <nil>
2021-08-23 15:22:17.720 [INFO][4152] startup/ipam.go 1966: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:17.814 [INFO][4152] startup/ipam.go 356: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:17.859 [INFO][4152] startup/ipam.go 470: Ran out of existing affine blocks for host host="kube-win"
2021-08-23 15:22:17.911 [ERROR][4152] startup/ipam.go 1663: Error validating ipam config error=global strict affinity should not be false for Windows node
2021-08-23 15:22:17.912 [ERROR][4152] startup/ipam.go 1987: Failed to ensure a block error=global strict affinity should not be false for Windows node
2021-08-23 15:22:17.914 [ERROR][4152] startup/ipam.go 1907: Error ensure IPv4 block: global strict affinity should not be false for Windows node
2021-08-23 15:22:17.914 [ERROR][4152] startup/startup.go 231: Unable to ensure network for os error=global strict affinity should not be false for Windows node
2021-08-23 15:22:17.915 [WARNING][4152] startup/startup.go 1347: Terminating
time="2021-08-23T15:22:17+02:00" level=error msg="Calico exited: exit status 1"
time="2021-08-23T15:22:20+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:22.003 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:22.013 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:22.013 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=9.949100000000001
2021-08-23 15:22:24.522 [INFO][5192] startup/startup.go 390: Early log level set to info
2021-08-23 15:22:24.527 [INFO][5192] startup/startup.go 406: Using NODENAME environment for node name kube-win
2021-08-23 15:22:24.528 [INFO][5192] startup/startup.go 418: Determined node name: kube-win
2021-08-23 15:22:24.599 [INFO][5192] startup/startup.go 103: Starting node kube-win with version v3.19.1
2021-08-23 15:22:24.615 [INFO][5192] startup/startup.go 115: Skipping datastore connection test
time="2021-08-23T15:22:25+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:25.724 [INFO][5192] startup/startup.go 774: Using autodetected IPv4 address on interface vEthernet (Ethernet): 172.16.1.83/24
2021-08-23 15:22:25.726 [INFO][5192] startup/startup.go 851: No AS number configured on node resource, using global value
2021-08-23 15:22:26.115 [INFO][5192] startup/startup.go 967: Selected default IP pool is '192.168.0.0/16'
2021-08-23 15:22:26.322 [INFO][5192] startup/startup.go 228: Using node name: kube-win
2021-08-23 15:22:26.324 [INFO][5192] startup/startup_windows.go 66: Backend networking is vxlan, ensure vxlan network.
2021-08-23 15:22:26.325 [INFO][5192] startup/ipam.go 1895: Ensure block for host kube-win, ipv4 attr &{3 1 windows-reserved-ipam-handle windows host rsvd} ipv6 attr <nil>
2021-08-23 15:22:26.401 [INFO][5192] startup/ipam.go 1966: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:26.812 [INFO][5192] startup/ipam.go 356: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:27.100 [INFO][5192] startup/ipam.go 470: Ran out of existing affine blocks for host host="kube-win"
2021-08-23 15:22:27.101 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:27.103 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:27.103 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=1.4307
2021-08-23 15:22:27.212 [ERROR][5192] startup/ipam.go 1663: Error validating ipam config error=global strict affinity should not be false for Windows node
2021-08-23 15:22:27.214 [ERROR][5192] startup/ipam.go 1987: Failed to ensure a block error=global strict affinity should not be false for Windows node
2021-08-23 15:22:27.216 [ERROR][5192] startup/ipam.go 1907: Error ensure IPv4 block: global strict affinity should not be false for Windows node
2021-08-23 15:22:27.218 [ERROR][5192] startup/startup.go 231: Unable to ensure network for os error=global strict affinity should not be false for Windows node
2021-08-23 15:22:27.219 [WARNING][5192] startup/startup.go 1347: Terminating
time="2021-08-23T15:22:27+02:00" level=error msg="Calico exited: exit status 1"
time="2021-08-23T15:22:30+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:32.105 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:32.112 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:32.112 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=6.3875
2021-08-23 15:22:35.025 [INFO][4616] startup/startup.go 390: Early log level set to info
2021-08-23 15:22:35.037 [INFO][4616] startup/startup.go 406: Using NODENAME environment for node name kube-win
2021-08-23 15:22:35.038 [INFO][4616] startup/startup.go 418: Determined node name: kube-win
2021-08-23 15:22:35.038 [INFO][4616] startup/startup.go 103: Starting node kube-win with version v3.19.1
2021-08-23 15:22:35.223 [INFO][4616] startup/startup.go 115: Skipping datastore connection test
time="2021-08-23T15:22:35+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:35.903 [INFO][4616] startup/startup.go 774: Using autodetected IPv4 address on interface vEthernet (Ethernet): 172.16.1.83/24
2021-08-23 15:22:35.905 [INFO][4616] startup/startup.go 851: No AS number configured on node resource, using global value
2021-08-23 15:22:36.414 [INFO][4616] startup/startup.go 967: Selected default IP pool is '192.168.0.0/16'
2021-08-23 15:22:36.802 [INFO][4616] startup/startup.go 228: Using node name: kube-win
2021-08-23 15:22:36.804 [INFO][4616] startup/startup_windows.go 66: Backend networking is vxlan, ensure vxlan network.
2021-08-23 15:22:36.809 [INFO][4616] startup/ipam.go 1895: Ensure block for host kube-win, ipv4 attr &{3 1 windows-reserved-ipam-handle windows host rsvd} ipv6 attr <nil>
2021-08-23 15:22:36.811 [INFO][4616] startup/ipam.go 1966: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:37.100 [INFO][4616] startup/ipam.go 356: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:37.113 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:37.114 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:37.114 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=0.9547
2021-08-23 15:22:37.209 [INFO][4616] startup/ipam.go 470: Ran out of existing affine blocks for host host="kube-win"
2021-08-23 15:22:37.407 [ERROR][4616] startup/ipam.go 1663: Error validating ipam config error=global strict affinity should not be false for Windows node
2021-08-23 15:22:37.408 [ERROR][4616] startup/ipam.go 1987: Failed to ensure a block error=global strict affinity should not be false for Windows node
2021-08-23 15:22:37.410 [ERROR][4616] startup/ipam.go 1907: Error ensure IPv4 block: global strict affinity should not be false for Windows node
2021-08-23 15:22:37.421 [ERROR][4616] startup/startup.go 231: Unable to ensure network for os error=global strict affinity should not be false for Windows node
2021-08-23 15:22:37.422 [WARNING][4616] startup/startup.go 1347: Terminating
time="2021-08-23T15:22:37+02:00" level=error msg="Calico exited: exit status 1"
time="2021-08-23T15:22:40+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:42.118 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:42.119 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:42.119 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=1.1722
2021-08-23 15:22:44.709 [INFO][3360] startup/startup.go 390: Early log level set to info
2021-08-23 15:22:44.712 [INFO][3360] startup/startup.go 406: Using NODENAME environment for node name kube-win
2021-08-23 15:22:44.807 [INFO][3360] startup/startup.go 418: Determined node name: kube-win
2021-08-23 15:22:44.900 [INFO][3360] startup/startup.go 103: Starting node kube-win with version v3.19.1
2021-08-23 15:22:45.117 [INFO][3360] startup/startup.go 115: Skipping datastore connection test
time="2021-08-23T15:22:45+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:46.017 [INFO][3360] startup/startup.go 774: Using autodetected IPv4 address on interface vEthernet (Ethernet): 172.16.1.83/24
2021-08-23 15:22:46.019 [INFO][3360] startup/startup.go 851: No AS number configured on node resource, using global value
2021-08-23 15:22:46.326 [INFO][3360] startup/startup.go 967: Selected default IP pool is '192.168.0.0/16'
2021-08-23 15:22:46.922 [INFO][3360] startup/startup.go 228: Using node name: kube-win
2021-08-23 15:22:46.928 [INFO][3360] startup/startup_windows.go 66: Backend networking is vxlan, ensure vxlan network.
2021-08-23 15:22:47.105 [INFO][3360] startup/ipam.go 1895: Ensure block for host kube-win, ipv4 attr &{3 1 windows-reserved-ipam-handle windows host rsvd} ipv6 attr <nil>
2021-08-23 15:22:47.118 [INFO][3360] startup/ipam.go 1966: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:47.120 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:47.121 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:47.121 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=1.738
2021-08-23 15:22:47.417 [INFO][3360] startup/ipam.go 356: Looking up existing affinities for host host="kube-win"
2021-08-23 15:22:47.504 [INFO][3360] startup/ipam.go 470: Ran out of existing affine blocks for host host="kube-win"
2021-08-23 15:22:47.603 [ERROR][3360] startup/ipam.go 1663: Error validating ipam config error=global strict affinity should not be false for Windows node
2021-08-23 15:22:47.607 [ERROR][3360] startup/ipam.go 1987: Failed to ensure a block error=global strict affinity should not be false for Windows node
2021-08-23 15:22:47.608 [ERROR][3360] startup/ipam.go 1907: Error ensure IPv4 block: global strict affinity should not be false for Windows node
2021-08-23 15:22:47.609 [ERROR][3360] startup/startup.go 231: Unable to ensure network for os error=global strict affinity should not be false for Windows node
2021-08-23 15:22:47.611 [WARNING][3360] startup/startup.go 1347: Terminating
time="2021-08-23T15:22:47+02:00" level=error msg="Calico exited: exit status 1"
time="2021-08-23T15:22:50+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:52.122 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:52.123 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:52.123 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=1.0736999999999999
time="2021-08-23T15:22:55+02:00" level=warning msg="can't find HNS endpoint for network, retryingExternal" error="Endpoint External not found"
2021-08-23 15:22:55.833 [INFO][6508] startup/startup.go 390: Early log level set to info
2021-08-23 15:22:55.905 [INFO][6508] startup/startup.go 406: Using NODENAME environment for node name kube-win
2021-08-23 15:22:55.919 [INFO][6508] startup/startup.go 418: Determined node name: kube-win
2021-08-23 15:22:55.922 [INFO][6508] startup/startup.go 103: Starting node kube-win with version v3.19.1
2021-08-23 15:22:56.125 [INFO][6508] startup/startup.go 115: Skipping datastore connection test
2021-08-23 15:22:57.208 [INFO][4548] felix/win_dataplane.go 299: Applying dataplane updates
2021-08-23 15:22:57.820 [WARNING][4548] felix/win_dataplane.go 340: CompleteDeferredWork returned an error - scheduling a retry error=didn't find any HNS networks matching regular expression (?i)calico.*
2021-08-23 15:22:57.821 [INFO][4548] felix/win_dataplane.go 306: Finished applying updates to dataplane. msecToApply=613.0155000000001
2021-08-23 15:22:58.022 [INFO][6508] startup/startup.go 774: Using autodetected IPv4 address on interface vEthernet (Ethernet): 172.16.1.83/24
2021-08-23 15:22:58.024 [INFO][6508] startup/startup.go 851: No AS number configured on node resource, using global value
time="2021-08-23T15:22:59+02:00" level=error msg="Tunnel endpoint watch channel closed: {ERROR &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding,Reason:InternalError,Details:&StatusDetails{Name:,Group:,Kind:,Causes:[]StatusCause{StatusCause{Type:UnexpectedServerResponse,Message:unable to decode an event from the watch stream: context canceled,Field:,},StatusCause{Type:ClientWatchDecoding,Message:unable to decode an event from the watch stream: context canceled,Field:,},},RetryAfterSeconds:0,UID:,},Code:500,}}"
time="2021-08-23T15:22:59+02:00" level=info msg="Proxy done" err="context canceled" url="wss://172.16.1.81:9345/v1-rke2/connect"
time="2021-08-23T15:22:59+02:00" level=error msg="Calico exited: exit status 2"
time="2021-08-23T15:22:59+02:00" level=info msg="Proxy done" err="context canceled" url="wss://172.16.1.80:9345/v1-rke2/connect"
time="2021-08-23T15:22:59+02:00" level=info msg="Proxy done" err="context canceled" url="wss://172.16.1.82:9345/v1-rke2/connect"
2021-08-23 15:22:59.112 [WARNING][4548] felix/daemon.go 716: Felix is shutting down reason="Received OS signal interrupt"
2021-08-23 15:22:59.112 [FATAL][4548] felix/daemon.go 787: Exiting immediately reason="Received OS signal interrupt"
time="2021-08-23T15:22:59+02:00" level=error msg="Kubelet exited: <nil>"
time="2021-08-23T15:22:59+02:00" level=error msg="Felix exited: exit status 1"
`

**Comment by phillipsj** [comment]
@MichaelTrip it looks like you don't have strict affinity configured correctly.

```
 Error ensure IPv4 block: global strict affinity should not be false for Windows node
```

That has been corrected and you will need to use the latest RC to get that fix. Once release 1.21.3-rke2r2 should have that corrected.

**Comment by MichaelTrip** [comment]
> @MichaelTrip it looks like you don't have strict affinity configured correctly.
> 
> ```
>  Error ensure IPv4 block: global strict affinity should not be false for Windows node
> ```
> 
> That has been corrected and you will need to use the latest RC to get that fix. Once release 1.21.3-rke2r2 should have that corrected.

Hi,

I just tried rke2.exe version v1.21.4+rke2r2 version and still see the same problem. Should i conigure the strict affinity on the rke2 on windows or also on my linux nodes?

**Comment by phillipsj** [comment]
@MichaelTrip hmm, I wonder how you ended up in the current state. Yes, you will need to enable it for your entire cluster. That setting prevents sharing ip blocks between linux and windows nodes.  Under the VXLAN section [here ](https://docs.projectcalico.org/getting-started/windows-calico/kubernetes/standard#install-calico-on-linux-control-and-worker-nodes) is the Calico command that needs executed.

**Comment by phillipsj** [comment]
How to check that is located here in the Calico docs: https://docs.projectcalico.org/getting-started/windows-calico/quickstart#configure-strict-affinity-for-clusters-using-calico-networking

It uses the calicoctl to check the configuration. It's easiest to do this from the server node.

**Comment by MichaelTrip** [comment]
That worked. I am now getting another error. I will open a new isue. I will close this one.
