### ISSUE TITLE
in SLES2/OpenSUSE rke2 services don't get restarted after reboot

### ISSUE THREAD

**Issue by wrkode** [rancher/rke2#737]
The issue is the unusual unpacking of the RKE2 tarball and unusual mount points of in default partitioning of SLES. In default installations of SLES/OpenSUSE we'll have /usr/local defined as a discrete mount point. This is an issue because systemd will try to bring the service up before mounting /usr/local.
to Keep RKE2 distro agnostic, In my opinion install.sh should unpack the .service files in /usr/lib/systemd/system/.

To solve the issue, after unpacking (run ./install.sh), I have moved the files to /usr/lib/systemd/system and ran "systemctl daemon-reload" and "systemctl enable rke2-server.service"

**Comment by brandond** [comment]
You might look into adding a `x-systemd.required-by=rke2-server.service option to the fstab entry:

https://www.freedesktop.org/software/systemd/man/systemd.mount.html

**Comment by wrkode** [comment]
> Why is it mounting /usr/local so late? You might look into adding a `x-systemd.required-by=rke2-server.service option to the fstab entry for /usr/local:
> 
> https://www.freedesktop.org/software/systemd/man/systemd.mount.html

**Comment by wrkode** [comment]
> Why is it mounting /usr/local so late? You might look into adding a `x-systemd.required-by=rke2-server.service option to the fstab entry for /usr/local:
> 
> https://www.freedesktop.org/software/systemd/man/systemd.mount.html

Hi Brandon,
thanks for the pointer, but personally, I wonder why systemd services are being registered/installed in /usr/local. I think that's not an appropriate location

**Comment by Martin-Weiss** [comment]
FYI - also created https://bugzilla.suse.com/show_bug.cgi?id=1182237

**Comment by cjellick** [comment]
Spoke briefly with @martin-weiss about this.

This manifests itself as the agent not coming back after a reboot.

@rancher-max or @ShylajaDevadiga can you test this and attempt to reprdouce please?

**Comment by brandond** [comment]
According to the systemd documentation, /usr/local/lib is an appropriate location for unit files - see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path

> /usr/local/lib/systemd/system | System units installed by the administrator
> /usr/lib/systemd/system | System units installed by the distribution package manager

The RKE2 units are NOT being installed by the distribution package manager, and should NOT go in /usr/lib
I would probably dig into why your host is mounting that partition so late that it is affecting systemd's ability to load units from a supported location.

**Comment by wrkode** [comment]
> According to the systemd documentation, /usr/local/lib is an appropriate location for our unit files - see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path
> 
> > /usr/local/lib/systemd/system | System units installed by the administrator
> > /usr/lib/systemd/system | System units installed by the distribution package manager
> 
> The RKE2 units are NOT being installed by the distribution package manager, and should NOT go in /usr/lib
> I would probably dig into why your host is mounting that partition so late that it is affecting systemd's ability to load units from a supported location.

Hi Brandon,

It's all fine that the at freedesktop.org they think that /usr/local... is the place where a SysAdmin should register unit files. in fact they can pretty much put them wherever they want, but it doesn't mean that is the appropriate place. Several distribution might have issue with that. I invite you to do a little research. you'll find several Issues opened where services are registered in /usr/local.

For our issue....
I've deployed several VMs/BareMetal and used both SLES and OpenSUSE.
The issue followed the definition of discrete mount point for /usr/local.

**supported locations**
As far as I know the only two "supported" locations for systemd unit files are /etc/systemd/system/ (where all units are soft linked) and /usr/lib/systemd/system...where the unit files are finally placed. All other locations are in fact accepted as conditionally valid.

for the moment I'll just manually copy the files to /usr/lib/systemd/system/....daemon-reload and enable the services.

**Comment by Martin-Weiss** [comment]
Just to add to this - "customization" or "adjustments" to given / installed services should go to /etc/systemd/system - due to that my workaround for the non working startup is to copy the rke2-server.service and rke2-agent.service files to /etc/systemd/system/

Could we check where the RHEL RPMs are storing the systemd unit files?

**Comment by Oats87** [comment]
@Martin-Weiss The RHEL RPMs use the macro for defining the unit dir i.e. `%{_unitdir}`: https://github.com/rancher/rke2-packaging/blob/master/rpm/centos7/server/rke2-server.spec#L34 which will land them in `/usr/lib/systemd/system`

**Comment by Oats87** [comment]
We had a discussion with our team around this issue.

The root cause of the issue is that we (RKE2) are placing RPMs in `/usr/local/systemd/system` when we are installing RKE2 via Tarball, as this follows convention as pointed @brandond above: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path 

Interestingly, analyzing the manpage for `systemd.unit` on a SLES 15 SP2 system, the table does appear to not have the `/usr/local/systemd/system` directory as a suitable load path like the upstream systemd documentation has it:

Upstream systemd:
```
Path | Description
-- | --
/etc/systemd/system.control | Persistent and transient configuration created using the dbus API
/run/systemd/system.control
/run/systemd/transient | Dynamic configuration for transient units
/run/systemd/generator.early | Generated units with high priority (see early-dir in systemd.generator(7))
/etc/systemd/system | System units created by the administrator
/run/systemd/system | Runtime units
/run/systemd/generator | Generated units with medium priority (see normal-dir in systemd.generator(7))
/usr/local/lib/systemd/system | System units installed by the administrator
/usr/lib/systemd/system | System units installed by the distribution package manager
/run/systemd/generator.late | Generated units with low priority (see late-dir in systemd.generator(7))
```

SLES 15 SP2:
```
       Table 1.  Load path when running in system mode
       (--system).
       ┌────────────────────────┬─────────────────────┐
       │Path                    │ Description         │
       ├────────────────────────┼─────────────────────┤
       │/etc/systemd/system     │ Local configuration │
       ├────────────────────────┼─────────────────────┤
       │/run/systemd/system     │ Runtime units       │
       ├────────────────────────┼─────────────────────┤
       │/usr/lib/systemd/system │ Units of installed  │
       │                        │ packages            │
       └────────────────────────┴─────────────────────┘
```

As such, we will likely need to figure out how to properly place the RPMs in the `/etc/systemd/system` directory if possible, as we should not be placing them in the `/usr/llib/systemd/system` directory as that is reserved for the system package manager.

**Comment by wrkode** [comment]
> As such, we will likely need to figure out how to properly place the unit files in the `/etc/systemd/system` directory if possible, as we should not be placing them in the `/usr/llib/systemd/system` directory as that is reserved for the system package manager.

Hi Oats,
thanks for reviewing this. I've discussed it with my team as well and indeed I was wrong to say that /usr/lib/systemd/system was a valid location for "manually" placing the unit files.

**Comment by brandond** [comment]
This should be fixed in the linked PR. We're going to install to /opt/rke2 if /usr/local is read-only or on a separate mountpoint, and move the units into /etc/systemd/system since the only other place that SLES will check for units isn't appropriate for us to be dropping content into.

**Comment by ShylajaDevadiga** [comment]
Validated the fix on rke2 version v1.20.4-rc3_rke2r1 using SLES 15 SP2 as well as on OpenSUSE-Leap-15.2

- Created a separate partition for  /usr/local during OS installation on vm using virtualbox
- Installed rke2, cluster is up and pods in running state.
- Rebooted the node
- Confirmed cluster is up and pods are accessible after reboot

**Comment by davidnuzik** [comment]
Fixed milestone; originally we thought this would not make it in for 1.20.4 release and it was in for 1.20.5. I just updated the milestone to reflect where this was actually fixed -- which is in v1.20.4+rke2r1 release.

**Comment by The-Loeki** [comment]
Unfortunately still does `DirectoryOrCreate` and still fails for me (Fedora CoreOS 33)
```
[root@novel-moray agent]# rke2 --version
rke2 version v1.20.4+rke2r1 (e0a5163fef9227fa6c19e5f597101d4939077793)
go version go1.15.8b5

[root@novel-moray agent]# grep read-only /var/lib/rancher/rke2/agent/logs/kubelet.log
E0312 19:40:36.083323   12870 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/host-path/435b18d1d687eafcf71c111090e00a8b-dir3 podName:435b18d1d687eafcf71c111090e00a8b nodeName:}" failed. No retries permitted until 2021-03-12 19:42:38.083280027 +0000 UTC m=+638.697991364 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"dir3\" (UniqueName: \"kubernetes.io/host-path/435b18d1d687eafcf71c111090e00a8b-dir3\") pod \"kube-apiserver-novel-moray\" (UID: \"435b18d1d687eafcf71c111090e00a8b\") : mkdir /usr/share/ca-certificates: read-only file system"
E0312 19:42:38.127623   12870 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/host-path/435b18d1d687eafcf71c111090e00a8b-dir3 podName:435b18d1d687eafcf71c111090e00a8b nodeName:}" failed. No retries permitted until 2021-03-12 19:44:40.127593569 +0000 UTC m=+760.742304906 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"dir3\" (UniqueName: \"kubernetes.io/host-path/435b18d1d687eafcf71c111090e00a8b-dir3\") pod \"kube-apiserver-novel-moray\" (UID: \"435b18d1d687eafcf71c111090e00a8b\") : mkdir /usr/share/ca-certificates: read-only file system"
```

### Offending mounts in /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
```
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: dir2
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: dir3
```

**Comment by brandond** [comment]
@The-Loeki this issue is solely concerning the install path, are you perhaps thinking of #765?

**Comment by The-Loeki** [comment]
related: #765

**Comment by The-Loeki** [comment]
hehe beat me to it ;) looks like that one properly solves it so I'll await landing of that
